upstream frontend {
    server frontend:3000;
}

upstream backend {
    server backend:9000;
}

server {
    listen 80;
    server_name localhost;

    # 1. ЗАПРОСЫ К API (Все запросы на /api уходят в Symfony)
    location ~ ^/(api|bundles|_profiler) {
        include fastcgi_params;
        fastcgi_pass backend;
        
        # Указываем точный путь к index.php ВНУТРИ контейнера 'api'
        fastcgi_param SCRIPT_FILENAME /app/public/index.php;
        fastcgi_param DOCUMENT_ROOT /app/public;
        
        # Передаем правильный URI для роутинга Symfony
        fastcgi_param REQUEST_URI $request_uri;
    }

    # 2. ВСЕ ОСТАЛЬНЫЕ ЗАПРОСЫ (Nuxt.js)
    location / {
        proxy_pass http://frontend;
        proxy_http_version 1.1;
        
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
